# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# alias
alias ls='ls -lh --color=auto'
alias ll='ls -lh --color=auto'
alias apt='sudo apt'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias gi="git-ignore"
#####################################################

# Save type history for completion and easier life
HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000
setopt appendhistory

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.zplug/init.zsh

zplug "romkatv/powerlevel10k", as:theme
zplug "zsh-users/zsh-autosuggestions"
zplug "softmoth/zsh-vim-mode"
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "Aloxaf/fzf-tab"
zplug "wting/autojump", as:command, hook-build:"python ./install.py"
# zplug "voronkovich/gitignore.plugin.zsh"
zplug "peterhurford/up.zsh"
zplug "hlissner/zsh-autopair", defer:2"
zplug "laggardkernel/git-ignore"

# Supports oh-my-zsh plugins and the like
zplug "plugins/git",   from:oh-my-zsh
zplug "plugins/sudo",   from:oh-my-zsh  ##press ese key twice
zplug "plugins/extract",   from:oh-my-zsh
zplug "plugins/autojump",  from:oh-my-zsh
zplug "plugins/cp",   from:oh-my-zsh    # show progress
zplug "plugins/git-open",   from:oh-my-zsh #open github page
zplug "plugins/colored-man-pages",   from:oh-my-zsh 

source ~/.custom_zshrc.zsh

# Load if "if" tag returns true
# zplug "lib/clipboard", from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]"

# Can manage local plugins
# zplug "~/.zsh", from:local


# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi


# Then, source plugins and add commands to $PATH
zplug load 

# 补全快捷键重设
bindkey '^\' autosuggest-accept

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export DISPLAY=:0.0
